#!/bin/bash

#
#  Docker Automated Build Hook
#

apt-get update
apt-get install -y wget

if [[ $GIT_TAG =~ ^[0-9.]+$ ]]; then
    version=$GIT_TAG
else
    git fetch --tags
    version=$(git describe $(git rev-list --tags --max-count=1) --tags)
fi

wget https://github.com/sigoden/wechat-devtools/releases/download/$version/wechat-devtools-$version.tar.xz
tar -xJf wechat-devtools-$version.tar.xz && mv wechat-devtools-$version "$DIRSTACK/dist"